Ajout d'un menu hamburger et amélioration de la vue des permanences en mobile (responsive)
Jojo144/compteur_du_gase pull request #102
Opened 2024-11-11 19:16 UTC by ghostinthemuf

2024-11-24 17:34 UTC, Jojo144 commented
Salut, merci pour la proposition !
Est-ce que c'est prêt à être relu ou est-ce que c'est encore un brouillon ?
Dans l'idéal ça serait cool de virer les changements d'indentation de la PR car ça rend la relecture difficile ...

2024-12-03 20:34 UTC, JocelynDelalande requested changes
J'ai mis inline quelques retours sur le code.

Sinon j'ai testé, le menu c'est nickel ! Mais je pense qu'il reste un souci, cf notamment cette scrollbar horizontale

![image](https://github.com/user-attachments/assets/dd8f41a8-a713-4bc0-9756-463a55037cc1).

Après @antoinegaillardpaloit  c'est comme tu veux pour le coup si tu veux rebosser un peu sur le responsive de la page ou si tu préfères qu'on merge en l'état (c'est déjà une amélioration).

2025-01-17 15:26 UTC, ghostinthemuf commented on base/templates/base/activity_board.html
> +            <th colspan="2">Permanencièr·es</th>
en fait j'ai carrément enlevé tous les attributs scope puisqu'ils sont inférés, cf. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th#usage_notes

2025-01-17 15:28 UTC, ghostinthemuf commented on base/templates/base/base.html
> -<head>
non c'était pas 100% du whitepsace, je pense que c'est mon ide qui a fait du zèle, j'ai mis à jour pour ne garder que les vrais changements de code :)

2025-01-17 15:33 UTC, ghostinthemuf commented
Merci pour vos retours !
J'ai enlevé les purs changements d'indentation, désolé pour ça j'avais pas fait gaffe, c'est mon ide qui a dû faire du zèle.

Par rapport à ta capture et ta question @JocelynDelalande : le scope de cette PR c'est vraiment juste d'ajouter un hamburger menu (+ quelques petites optis sur la page des permanences pour la rendre plus lisible en mobile), mais le responsive sur toute l'app c'est un chantier plus global, je pense qu'on va pouvoir procéder par petites PR incrémentales :)

2025-01-17 16:07 UTC, JocelynDelalande approved these changes

2025-01-17 16:07 UTC, JocelynDelalande commented
Helle we gooo :)

2025-01-17 16:11 UTC, merged