Intagration du tableau des permanences
Jojo144/compteur_du_gase pull request #20
Opened 2020-10-04 19:59 UTC by Jojo144

2020-10-04 20:19 UTC, Jojo144 commented
Petit warning : cette PR n'implémente pas le système de permission pour déprotéger la page d'accueil pour l'instant.

J'ai l'impression que le plus simple serait de mettre toutes les urls privées (donc toutes sauf celle de la page d'accueil) derrière un `/p`

Exemple : `http://localhost:8000/p/produit/58` au lieu de `http://localhost:8000/produit/58`

@JocelynDelalande Un avis ?

Référence : https://yunohost.org/#/groups_and_permissions (section Notes for app packagers)

2020-10-04 20:44 UTC, JocelynDelalande commented
Oui : on peut utiliser `*_regexp` et attendre que le mécanisme des permissions supporte les regexp. Le seul truc que l'on perdra en attendant c'est que l'on ne pourra pas modifier depuis l'interface le choix de laisser l'accueil public ou non.

Même si déprécié, cette fonctionnalité est encore documentée et ne contient pas d'alternative pour l'heure (le workaround documenté utilise l'ancien mécanisme).

Quand ynh aura implém les regexp dans le nouveau système de permissions (la doc suggère que ça sera le cas) on pourra passer sur les « jolies » permissions sans trop d'efforts.

Le workaround détaillé en fin de doc me semble trop bordélique pour valoir le coup pour nous.

2020-10-05 12:45 UTC, JocelynDelalande requested changes

2020-10-05 12:45 UTC, JocelynDelalande commented on base/templates/base/activity_board.html
> +	<td><div style="width:100%; overflow:scroll">{{ activity.comment }}</div></td>
Le overflow: scroll fait un truc moche :

![image](https://user-images.githubusercontent.com/429633/95080495-76e10500-0718-11eb-9332-e7ba998632ad.png)

2020-10-05 12:45 UTC, JocelynDelalande commented on base/templates/base/activity_board.html
> +  <p><button class="btn btn-info collapsed" type="button" data-toggle="collapse" data-target="#collapseExample">
collapseExample ? résidu de copier-coller détecté !

Mode curieux et surpris : je ne comprends pas trop, il y a un bout de JS qui gère ce fonctionnement de collapse ? C'est quoi la magie ? :)

2020-10-05 12:47 UTC, JocelynDelalande commented
J'ai fait ma part via #25 :blush: , n'hésite pas à faire des retours si tu en as sur cette PR :-). Et une fois que tu as merge ma PR (pas avant plz, sinon ça va être le bazar) dasn la tienne, pense à faire un rebase de ta PR :et il y aura probablement une migration de merge à créer.

2020-10-05 19:30 UTC, Jojo144 commented on base/views.py
> +    dates = [date.today()]
Absolument aucun

2020-10-05 19:51 UTC, Jojo144 commented on base/templates/base/activity_board.html
> +  <p><button class="btn btn-info collapsed" type="button" data-toggle="collapse" data-target="#collapseExample">
Manuel de magie : https://getbootstrap.com/docs/4.0/components/collapse/#via-data-attributes

2020-10-05 21:13 UTC, merged